name: CI / CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'azure/terraform/**'
      - 'adr/**'
      - 'README.md'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - name: Install Azure Functions Core Tools
        run: npm i -g azure-functions-core-tools@4 --unsafe-perm true
      - run: npm ci
      - run: npm run validate
      - run: npm run test
        env:
          VITE_APP_INSIGHTS_CONNECTION_STRING: "InstrumentationKey=some-fun-key;IngestionEndpoint=http://localhost"
      - run: npm run test:unit:adapters
        env:
          COSMOS_DB_ENDPOINT: ${{ secrets.COSMOS_DB_ENDPOINT }}
          COSMOS_DB_READ_WRITE_KEY: ${{ secrets.COSMOS_DB_READ_WRITE_KEY }}
          COSMOS_DB_NAME: ${{ secrets.COSMOS_DB_NAME }}
          RUNNER_KEY: ${{ github.run_id }}

  build_and_deploy_job:
    needs: test
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          VITE_APP_INSIGHTS_CONNECTION_STRING: ${{ secrets.VITE_APP_INSIGHTS_CONNECTION_STRING }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "azure/api"
          output_location: "azure/build/display"
          app_build_command: "npm run build:display"
