name: CI / CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run validate
      - run: npm run test

  build_and_deploy_job:
    needs: test
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          VITE_APP_INSIGHTS_CONNECTION_STRING: ${{ secrets.VITE_APP_INSIGHTS_CONNECTION_STRING }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: "azure/api"
          output_location: "azure/build/display"
          app_build_command: "npm run build:display"
